# Generated by Django 3.2 on 2021-04-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlycharge',
            options={'ordering': ['reference'], 'verbose_name': 'Monthly Charges', 'verbose_name_plural': 'Monthly Charges'},
        ),
        migrations.AlterModelOptions(
            name='othercharge',
            options={'ordering': ['type_charge'], 'verbose_name': 'Other Charges', 'verbose_name_plural': 'Other Charges'},
        ),
        migrations.AlterModelOptions(
            name='paymentstat',
            options={'verbose_name': 'Payment Staus', 'verbose_name_plural': 'Payment Staus'},
        ),
        migrations.AlterField(
            model_name='monthlycharge',
            name='status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('UnPaid', 'UnPaid')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='othercharge',
            name='status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('UnPaid', 'UnPaid')], max_length=150, null=True),
        ),
    ]
