# Generated by Django 3.2 on 2021-04-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0002_auto_20210427_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentStat',
        ),
    ]
