# Generated by Django 3.2 on 2021-04-30 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('OrderRequest', '0002_auto_20210427_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Complete Address ( Incase of porting)'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='category_request',
            field=models.CharField(blank=True, choices=[('Connect to CallMe.Com.Ph', 'Connect to CallMe.Com.Ph'), ('Connect to PsalmsGlobal', 'Connect to PsalmsGlobal'), ('Personal Use', 'Personal Use'), ('Business Use', 'Business Use'), ('Others', 'Others')], max_length=150, null=True, verbose_name='Category Of Request'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client', verbose_name='Company Name ( That will appear in your caller ID)'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='fax',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=150, null=True, verbose_name='Do You Need Fax?'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='order_status',
            field=models.CharField(blank=True, choices=[('New Order', 'New Order'), ('Pending Request', 'Pending Request'), ('Processing', 'Processing'), ('Follow-up with the Client', 'Follow-up with the Client'), ('Declined', 'Declined'), ('Order Complete', 'Order Complete')], max_length=150, null=True, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='total Number Of Phone Lines Needed'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='preferred_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prepared Area Code'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='request',
            field=models.CharField(blank=True, choices=[('New Number Request', 'New Number Request'), ('Porting Request', 'Porting Request'), ('Other Request', 'Other Request')], max_length=150, null=True, verbose_name='Type Of Request'),
        ),
    ]
